name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # manual

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
          - macos-latest
        java-version:
          - 11
          - 17
          - 21
        maven:
          - 3.9.9
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Build distribution
        run: ./gradlew installDist
      - name: Run script
        run: ./build/install/jruby-open3-test/bin/jruby-open3-test src/main/resources/script.rb